import DashboardSidebar from '@/components/shared/DashboardSidebar';
import Footer from '@/components/shared/Footer';

export const metadata = {
  title: 'Amplify Research | Dashboard',
  description: 'Generated by create next app',
};

export default function DashboardLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen flex flex-col">
          {/* upper div */}
          <div className="flex-grow">
            <div className='flex justify-center items-center '>
<DashboardSidebar/>
<div className='flex-grow'>   {children}</div>
            </div>
          </div>
          {/* footer */}

          <Footer />
        </div>
      </body>
    </html>
  );
}
