import DashboardSidebar from "@/components/shared/DashboardSidebar";
import Footer from "@/components/shared/Footer";

export const metadata = {
  title: "Amplify Research | Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen flex flex-col h-full">
          {/* upper div */}
          <div className="flex-grow h-full">
            <div className="flex justify-center items-center h-full">
              <DashboardSidebar />
              <div className="flex-grow h-full"> {children}</div>
            </div>
          </div>
          {/* footer */}

          <Footer />
        </div>
      </body>
    </html>
  );
}
